version: '3'
services:

  dashboard:
    image: dash_app:1.0
    container_name: dash_dashboard
    restart: always
    ports:
      - 8050:8050
    volumes:
      - ./gcode:/wd/gcode
    networks:
      - network 

networks:
  network:
    driver: bridge